#!/usr/bin/env python3
"""
Demo script to show the AI disclaimer implementation in Slack
Creates a visual representation of how the disclaimer appears in Slack summaries
"""

import json
from datetime import datetime

def create_demo_summary_with_disclaimer():
    """Create a demo Slack block structure showing the disclaimer"""
    
    # Mock summary data
    mock_overview = {
        'incident_status': 'Ongoing',
        'total_messages_analyzed': 45,
        'significant_events': 8,
        'categories_detected': {'diagnostics': 3, 'actions': 2, 'impact': 1, 'resolution': 2}
    }
    
    mock_executive_summary = "Database latency spike detected at 14:30. Team investigating connection pool issues. Rollback to previous version initiated. Customer impact limited to EU region."
    
    mock_action_items = [
        {'description': 'Monitor database connection pool metrics', 'status': 'pending'},
        {'description': 'Prepare rollback plan for payment service', 'status': 'in_progress'},
        {'description': 'Update customer status page', 'status': 'completed'}
    ]
    
    # Create Slack blocks with disclaimer (same structure as slack_bot.py)
    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": "🤖 Incident Analysis Summary"
            }
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn", 
                "text": "⚠️ *IMPORTANT DISCLAIMER:* Always review AI generated content prior to use. This analysis is generated by AI and may contain inaccuracies or miss important details."
            }
        },
        {
            "type": "divider"
        },
        {
            "type": "section",
            "fields": [
                {
                    "type": "mrkdwn",
                    "text": f"*Status:* {mock_overview['incident_status']}"
                },
                {
                    "type": "mrkdwn",
                    "text": f"*Messages Analyzed:* {mock_overview['total_messages_analyzed']}"
                },
                {
                    "type": "mrkdwn",
                    "text": f"*Significant Events:* {mock_overview['significant_events']}"
                },
                {
                    "type": "mrkdwn",
                    "text": f"*Categories:* {', '.join([f'{k}:{v}' for k,v in mock_overview['categories_detected'].items() if v > 0])}"
                }
            ]
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Executive Summary:*\n{mock_executive_summary}"
            }
        }
    ]
    
    # Add action items
    action_text = ""
    for item in mock_action_items:
        status_icon = "✅" if item['status'] == 'completed' else "⏳" if item['status'] == 'pending' else "💡"
        action_text += f"{status_icon} {item['description']}\n"
    
    blocks.append({
        "type": "section",
        "text": {
            "type": "mrkdwn",
            "text": f"*Key Actions:*\n{action_text}"
        }
    })
    
    # Add feedback section
    blocks.extend([
        {
            "type": "divider"
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": "*Help us improve!* 📋"
            },
            "accessory": {
                "type": "button",
                "text": {
                    "type": "plain_text",
                    "text": "Give Feedback",
                    "emoji": True
                },
                "url": "https://docs.google.com/forms/d/e/1FAIpQLScs50MAteC0TZ2YefvXJHtKw1PZUeqSRy3PDpuiGXk6FIMnqw/viewform",
                "action_id": "feedback_button"
            }
        },
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": f"⚠️ Always review AI generated content prior to use • Generated by Claude Incident Analyzer • {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
                }
            ]
        }
    ])
    
    return blocks

def generate_visual_representation():
    """Generate a text representation of how the Slack message will look"""
    
    print("=" * 80)
    print("SLACK MESSAGE PREVIEW - AI DISCLAIMER IMPLEMENTATION")
    print("=" * 80)
    print()
    print("🤖 Incident Analysis Summary")
    print("-" * 50)
    print()
    print("⚠️  IMPORTANT DISCLAIMER: Always review AI generated content prior to use.")
    print("    This analysis is generated by AI and may contain inaccuracies or miss")
    print("    important details.")
    print()
    print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    print()
    print("Status: Ongoing                    Messages Analyzed: 45")
    print("Significant Events: 8              Categories: diagnostics:3, actions:2, impact:1, resolution:2")
    print()
    print("Executive Summary:")
    print("Database latency spike detected at 14:30. Team investigating connection")
    print("pool issues. Rollback to previous version initiated. Customer impact")
    print("limited to EU region.")
    print()
    print("Key Actions:")
    print("⏳ Monitor database connection pool metrics")
    print("💡 Prepare rollback plan for payment service")
    print("✅ Update customer status page")
    print()
    print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    print()
    print("Help us improve! 📋                                    [Give Feedback]")
    print()
    print("⚠️  Always review AI generated content prior to use • Generated by Claude")
    print(f"   Incident Analyzer • {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print()
    print("=" * 80)
    print()
    print("KEY DISCLAIMER FEATURES IMPLEMENTED:")
    print("✅ Prominent warning at the top of every summary")
    print("✅ Clear message: 'Always review AI generated content prior to use'")
    print("✅ Additional context about potential AI limitations")
    print("✅ Reminder in footer for persistent visibility")
    print("✅ Warning emoji (⚠️) for visual prominence")
    print()
    print("COMPLIANCE NOTES:")
    print("• Disclaimer appears in every AI-generated summary")
    print("• Visible both at top and bottom of message")
    print("• Clear language about reviewing content before use")
    print("• Warns about potential inaccuracies and missed details")
    print("=" * 80)

def save_demo_json():
    """Save the demo Slack blocks to a JSON file for reference"""
    blocks = create_demo_summary_with_disclaimer()
    
    demo_message = {
        "text": "🤖 Incident Analysis Summary",
        "blocks": blocks,
        "disclaimer_implemented": True,
        "disclaimer_locations": [
            "Top of message - prominent warning section",
            "Bottom of message - footer reminder"
        ],
        "disclaimer_text": "Always review AI generated content prior to use",
        "implementation_date": datetime.now().isoformat()
    }
    
    with open('slack_disclaimer_demo.json', 'w') as f:
        json.dump(demo_message, f, indent=2)
    
    print(f"Demo JSON saved to: slack_disclaimer_demo.json")

if __name__ == "__main__":
    print("Generating AI Disclaimer Implementation Demo...\n")
    generate_visual_representation()
    save_demo_json()
    
    # Also save the blocks structure
    blocks = create_demo_summary_with_disclaimer()
    print(f"\nSlack Blocks JSON structure saved for testing.")
    print("This demonstrates the exact implementation in the Slack bot.")